### ISSUE TITLE
"To use the completation you need to setup Funkin Directory first!"

### ISSUE THREAD

**Issue by amyspark-ng** [Snirozu/Funkin-Script-AutoComplete#11]
Not sure what it actually means, i'm sorry, how do i work this out?

**Comment by Snirozu** [comment]
click the install library button and it will install the fnf source code as a haxelib
or if you already have the fnf source directory then bind a haxelib named `funkin` to the `source/` folder

**Comment by amyspark-ng** [comment]
i will try thank you

**Comment by amyspark-ng** [comment]
if i have the game's source code instead, where would i place it? since the install library button doesn't work for me

**Comment by amyspark-ng** [comment]
if i have the game's source code instead, where would i place it? since the install library button doesn't work for me

**Comment by Snirozu** [comment]
the source code can be anywhere
if you want to setup the haxelib for it then use this command in the root repository directory of it:
`haxelib dev funkin /source/`

**Comment by amyspark-ng** [comment]
i think im close to having it work :) what do i do with these errors?
![image](https://github.com/user-attachments/assets/d5a12eec-7cc2-483a-bf6a-459329d78a93)

**Comment by Snirozu** [comment]
try latest build for thx fix, also is your openfl version the latest?

**Comment by amyspark-ng** [comment]
not home right now, ill check openfl and try newest version thank you

**Comment by amyspark-ng** [comment]
![image](https://github.com/user-attachments/assets/0cd9c133-6e49-498c-8231-a80244005276)

this is my version of openfl

also not sure if i may be using the extension's wrong version, on installation in the README i clicked latest build and downloaded this one

![image](https://github.com/user-attachments/assets/4bc39471-0707-4ac8-a4b2-6fc08947353b)

**Comment by Snirozu** [comment]
yeah the openfl version is correct, it's with the haxe completion server because it sometimes refuses to work so weird errors like this can happen

i would wait for haxe 5 and then test the completion because they (i hope they're gonna make it better)

**Comment by amyspark-ng** [comment]
ok, i'll be closing for now then, thank you for helping!
